/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-variant': '#dfe3e1',
        'tertiary-fixed': '#ffdbd1',
        'on-tertiary-fixed': '#3b0900',
        'on-tertiary-fixed-variant': '#743320',
        'on-error-container': '#93000a',
        'primary-container': '#0e7c6b',
        'secondary': '#325f9b',
        'inverse-surface': '#2d3130',
        'surface-container-high': '#e5e9e6',
        'outline': '#6e7a76',
        'surface-container-low': '#f0f5f2',
        'inverse-primary': '#7bd7c3',
        'on-secondary-fixed-variant': '#124782',
        'primary-fixed': '#98f3de',
        'on-error': '#ffffff',
        'on-tertiary-container': '#ffeeea',
        'error-container': '#ffdad6',
        'error': '#ba1a1a',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed': '#00201a',
        'tertiary-container': '#a55943',
        'surface-container': '#ebefec',
        'surface-bright': '#f6faf7',
        'surface-tint': '#006b5c',
        'surface': '#f6faf7',
        'on-secondary-container': '#194b86',
        'secondary-fixed': '#d5e3ff',
        'primary-fixed-dim': '#7bd7c3',
        'tertiary': '#87422d',
        'on-secondary': '#ffffff',
        'background': '#f6faf7',
        'primary': '#006153',
        'on-tertiary': '#ffffff',
        'on-surface': '#181d1b',
        'secondary-fixed-dim': '#a7c8ff',
        'on-background': '#181d1b',
        'surface-container-highest': '#dfe3e1',
        'inverse-on-surface': '#eef2ef',
        'surface-dim': '#d7dbd8',
        'outline-variant': '#bdc9c5',
        'on-primary': '#ffffff',
        'tertiary-fixed-dim': '#ffb5a0',
        'on-surface-variant': '#3e4946',
        'on-primary-container': '#bdffee',
        'secondary-container': '#93bdff',
        'on-primary-fixed-variant': '#005145',
        'on-secondary-fixed': '#001c3b',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'lg': '48px',
        'container-max': '1280px',
        'md': '24px',
        'gutter': '24px',
        'base': '8px',
        'sm': '12px',
        'xs': '4px',
        'xl': '80px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'label-caps': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-xl': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'mono-label': ['JetBrains Mono', 'monospace'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-sm': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'mono-label': ['13px', { lineHeight: '1', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
};

export default config;
